try {
    let divisor = 0
    let num = 30
    
    let operacao = num / divisor;

} catch (error) {
    console.erro("Erro:", error.message);
}